# Generated by Django 5.2.13 on 2026-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='Train_name',
            field=models.TextField(max_length=50),
        ),
    ]
