# Generated by Django 5.2.13 on 2026-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainapp', '0002_alter_train_train_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='Train_name',
            field=models.CharField(max_length=50),
        ),
    ]
